name: home_tasks_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.9
  go_router: ^13.2.4
  hive: ^2.2.3
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
